auto: false
server: false
lsi: false
markdown: kramdown
kramdown:
    parse_block_html: true;
pygments: true
permalink: /:year/:month/:title
paginate: 10
category_dir: topics
category_title_prefix: 
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp"]
#destination: public
